# Generated by Django 5.1.3 on 2024-12-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_sales_discountamt_alter_customer_id_alter_items_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sdiscountAmt',
            field=models.FloatField(null=True),
        ),
    ]
